// AUTO-GENERATED: Hindi translations for EV notableFeatures bullets.
// Keys are the exact English feature strings from lib/ev-data.ts.
// Acronyms, brand/model names and numbers are intentionally kept in English.
// Regenerate if notableFeatures change.

export const FEATURE_HI: Record<string, string> = {
  "0-100 in 2.95s (Eletre R)": "0-100 in 2.95s (Eletre R)",
  "0-100 in 3.2s": "0-100 in 3.2s",
  "0-100 in 4.5s": "0-100 in 4.5s",
  "0-50 km/h in 4.2s": "0-50 km/h in 4.2s",
  "10 kW liquid-cooled motor": "10 kW लिक्विड-कूल्ड मोटर",
  "10 kW motor": "10 kW मोटर",
  "10-inch TFT touchscreen": "10-inch TFT टचस्क्रीन",
  "10-inch touchscreen": "10-inch टचस्क्रीन",
  "10-year battery warranty": "10-साल बैटरी वारंटी",
  "10.2-inch TFT touchscreen": "10.2-inch TFT टचस्क्रीन",
  "10.2-inch touchscreen": "10.2-inch टचस्क्रीन",
  "100cc-equivalent performance": "100cc-समान परफॉर्मेंस",
  "102 kWh battery": "102 kWh बैटरी",
  "10A smart charger": "10A स्मार्ट चार्जर",
  "11 airbags": "11 एयरबैग",
  "11 kW mid-drive motor": "11 kW मिड-ड्राइव मोटर",
  "11 kW motor": "11 kW मोटर",
  "11.6L frunk": "11.6L फ्रंक",
  "112 kWh battery": "112 kWh बैटरी",
  "118+ connected features": "118+ कनेक्टेड फीचर्स",
  "12 kW hub motor": "12 kW हब मोटर",
  "12 kW motor": "12 kW मोटर",
  "12 L front glovebox": "12 L फ्रंट ग्लवबॉक्स",
  "12-inch alloys": "12-inch अलॉय",
  "12.3-inch touchscreen": "12.3-inch टचस्क्रीन",
  "12.9-inch touchscreen": "12.9-inch टचस्क्रीन",
  "120 km/h top speed": "120 km/h टॉप स्पीड",
  "13 kW motor": "13 kW मोटर",
  "13 kW peak motor": "13 kW पीक मोटर",
  "14-inch front wheel": "14-inch फ्रंट व्हील",
  "14.5-inch touchscreen": "14.5-inch टचस्क्रीन",
  "15-inch touchscreen": "15-inch टचस्क्रीन",
  "15.4-inch touchscreen": "15.4-inch टचस्क्रीन",
  "15.6-inch rotating screen": "15.6-inch घूमने वाली स्क्रीन",
  "15.6-inch touchscreen": "15.6-inch टचस्क्रीन",
  "150 km Eco range": "150 km Eco रेंज",
  "150L frunk + 663L boot": "150L फ्रंक + 663L बूट",
  "16-inch alloy wheels": "16-inch अलॉय व्हील",
  "17-inch alloy wheels": "17-inch अलॉय व्हील",
  "170 km claimed range": "170 km दावा की गई रेंज",
  "175 kW fast charging": "175 kW फास्ट चार्जिंग",
  "18-inch front wheel": "18-inch फ्रंट व्हील",
  "2-5 kWh battery options": "2-5 kWh बैटरी विकल्प",
  "200 km claimed range": "200 km दावा की गई रेंज",
  "200 Nm peak torque": "200 Nm पीक टॉर्क",
  "250 km claimed range": "250 km दावा की गई रेंज",
  "250W motor": "250W मोटर",
  "265 km claimed range": "265 km दावा की गई रेंज",
  "270 kW fast charging": "270 kW फास्ट चार्जिंग",
  "3 kW hub motor": "3 kW हब मोटर",
  "3 kW motor": "3 kW मोटर",
  "3 kW motor, 72V": "3 kW मोटर, 72V",
  "30 kW motor": "30 kW मोटर",
  "31.3-inch rear Theatre Screen": "31.3-inch रियर Theatre Screen",
  "320 km claimed range": "320 km दावा की गई रेंज",
  "35 L boot": "35 L बूट",
  "350 kW ultra-fast charging": "350 kW अल्ट्रा-फास्ट चार्जिंग",
  "360-degree camera": "360-डिग्री कैमरा",
  "4 ride modes": "4 राइड मोड",
  "4-speed manual gearbox": "4-स्पीड मैनुअल गियरबॉक्स",
  "4.3-inch LCD": "4.3-inch LCD",
  "4.3-inch TFT": "4.3-inch TFT",
  "43 L under-seat storage": "43 L अंडर-सीट स्टोरेज",
  "4680 Bharat Cell": "4680 Bharat Cell",
  "475 km WLTP range": "475 km WLTP रेंज",
  "49 & 61 kWh options": "49 और 61 kWh विकल्प",
  "490 km range": "490 km रेंज",
  "4MATIC AWD": "4MATIC AWD",
  "5 kW BLDC hub motor": "5 kW BLDC हब मोटर",
  "5 kW hub motor": "5 kW हब मोटर",
  "5+ metre flagship SUV": "5+ मीटर फ्लैगशिप SUV",
  "5-inch LCD": "5-inch LCD",
  "5-inch LCD with app": "5-inch LCD ऐप के साथ",
  "5-inch TFT": "5-inch TFT",
  "5-star Bharat NCAP": "5-स्टार Bharat NCAP",
  "5.5-inch touchscreen": "5.5-inch टचस्क्रीन",
  "52 kW motor": "52 kW मोटर",
  "530 km WLTP range": "530 km WLTP रेंज",
  "531 km claimed range": "531 km दावा की गई रेंज",
  "535 km claimed range": "535 km दावा की गई रेंज",
  "550 km claimed range": "550 km दावा की गई रेंज",
  "56 L total storage": "56 L कुल स्टोरेज",
  "560 km claimed range": "560 km दावा की गई रेंज",
  "59/70/79 kWh options": "59/70/79 kWh विकल्प",
  "590 km claimed range": "590 km दावा की गई रेंज",
  "5yr/75,000 km battery warranty": "5yr/75,000 km बैटरी वारंटी",
  "6 airbags standard": "6 एयरबैग स्टैंडर्ड",
  "6-inch LCD display": "6-inch LCD डिस्प्ले",
  "6-seat captain chairs": "6-सीट कैप्टन चेयर",
  "6-seater 3-row layout": "6-सीटर 3-रो लेआउट",
  "6/7-seat options": "6/7-सीट विकल्प",
  "6/7-seater electric MPV": "6/7-सीटर इलेक्ट्रिक MPV",
  "600 km range": "600 km रेंज",
  "635 km claimed range": "635 km दावा की गई रेंज",
  "649 bhp": "649 bhp",
  "661 km WLTP range": "661 km WLTP रेंज",
  "681 km range": "681 km रेंज",
  "7 airbags + ADAS": "7 एयरबैग + ADAS",
  "7-inch Android display": "7-inch Android डिस्प्ले",
  "7-inch TFT": "7-inch TFT",
  "7-inch TFT Ather Stack 6": "7-inch TFT Ather Stack 6",
  "7-inch TFT RoadSync Duo": "7-inch TFT RoadSync Duo",
  "7-inch TFT touchscreen": "7-inch TFT टचस्क्रीन",
  "7-inch touchscreen": "7-inch टचस्क्रीन",
  "7-seat electric SUV": "7-सीट इलेक्ट्रिक SUV",
  "7-seat flagship SUV": "7-सीट फ्लैगशिप SUV",
  "7.5 kW BLDC motor": "7.5 kW BLDC मोटर",
  "70.5 kWh battery": "70.5 kWh बैटरी",
  "72V lithium-ion battery": "72V लिथियम-आयन बैटरी",
  "8 airbags + Level 2 ADAS": "8 एयरबैग + Level 2 ADAS",
  "8.44 kWh large battery": "8.44 kWh बड़ी बैटरी",
  "8.8 kW peak motor": "8.8 kW पीक मोटर",
  "800V architecture": "800V आर्किटेक्चर",
  "800V dual-motor AWD": "800V डुअल-मोटर AWD",
  "800V E-GMP architecture": "800V E-GMP आर्किटेक्चर",
  "809 km claimed range": "809 km दावा की गई रेंज",
  "81-litre frunk": "81-लीटर फ्रंक",
  "857 km ARAI range": "857 km ARAI रेंज",
  "9.4 kW mid-mounted motor": "9.4 kW मिड-माउंटेड मोटर",
  "ABS with disc brakes": "डिस्क ब्रेक के साथ ABS",
  "Active aerodynamic winglets": "एक्टिव एयरोडायनामिक विंगलेट्स",
  "Advanced HUD": "एडवांस्ड HUD",
  "Aero-lounge cabin": "एयरो-लाउंज केबिन",
  "Affordable commuter": "किफायती कम्यूटर",
  "Affordable commuter EV": "किफायती कम्यूटर EV",
  "Affordable entry Chetak": "किफायती एंट्री Chetak",
  "Affordable entry EV": "किफायती एंट्री EV",
  "AI-enabled sounds": "AI-इनेबल्ड साउंड्स",
  "Air suspension": "एयर सस्पेंशन",
  "All-LED lighting": "ऑल-LED लाइटिंग",
  "All-new in-house EV platform": "बिल्कुल नया इन-हाउस EV प्लेटफॉर्म",
  "Alloy wheels": "अलॉय व्हील्स",
  "Alloy wheels, tubeless tyres": "अलॉय व्हील्स, ट्यूबलेस टायर",
  "Aluminium swingarm": "एल्युमिनियम स्विंगआर्म",
  "Aluminium/magnesium frame": "एल्युमिनियम/मैग्नीशियम फ्रेम",
  "Anti-theft alarm": "एंटी-थेफ्ट अलार्म",
  "Anti-theft lock": "एंटी-थेफ्ट लॉक",
  "App connectivity": "ऐप कनेक्टिविटी",
  "AR head-up display": "AR हेड-अप डिस्प्ले",
  "Arcade.ev app suite": "Arcade.ev ऐप सूट",
  "Assembled in Tamil Nadu": "तमिलनाडु में असेंबल्ड",
  "Ather Grid fast charging": "Ather Grid फास्ट चार्जिंग",
  "Augmented reality HUD": "ऑगमेंटेड रियलिटी HUD",
  "Autopilot": "ऑटोपायलट",
  "AWD dual motor": "AWD डुअल मोटर",
  "Axial flux motor": "एक्सियल फ्लक्स मोटर",
  "BaaS option": "BaaS विकल्प",
  "BaaS pricing": "BaaS प्राइसिंग",
  "BaaS pricing option": "BaaS प्राइसिंग विकल्प",
  "BaTRics battery tech": "BaTRics बैटरी टेक",
  "Battery subscription option": "बैटरी सब्सक्रिप्शन विकल्प",
  "Battery swap (BaaS) option": "बैटरी स्वैप (BaaS) विकल्प",
  "Battery-as-a-Service option": "Battery-as-a-Service विकल्प",
  "Belt drive": "बेल्ट ड्राइव",
  "Best-selling EV in India": "भारत में सबसे ज़्यादा बिकने वाली EV",
  "Blade battery": "ब्लेड बैटरी",
  "Blade LFP battery": "ब्लेड LFP बैटरी",
  "BLDC hub motor": "BLDC हब मोटर",
  "Bluetooth app connectivity": "Bluetooth ऐप कनेक्टिविटी",
  "Bluetooth, OTA updates": "Bluetooth, OTA अपडेट्स",
  "BMW Curved Display": "BMW कर्व्ड डिस्प्ले",
  "Bowers & Wilkins audio": "Bowers & Wilkins ऑडियो",
  "Brake-by-wire": "ब्रेक-बाय-वायर",
  "Budget electric SUV": "बजट इलेक्ट्रिक SUV",
  "Built for gig/delivery": "गिग/डिलीवरी के लिए बना",
  "Captain chairs with recline": "रिक्लाइन वाली कैप्टन चेयर्स",
  "Carbon-fibre bodywork": "कार्बन-फाइबर बॉडीवर्क",
  "CBS braking": "CBS ब्रेकिंग",
  "Charge anywhere": "कहीं भी चार्ज करें",
  "Cheapest Volvo in India": "भारत में सबसे सस्ती Volvo",
  "City commuter": "सिटी कम्यूटर",
  "City-focused": "सिटी-केंद्रित",
  "Claimed 501 km range": "दावा की गई 501 km रेंज",
  "Claimed sub-2s 0-60": "दावा किया गया sub-2s 0-60",
  "Co-developed with River Mobility": "River Mobility के साथ मिलकर विकसित",
  "Co-developed with Zero Motorcycles": "Zero Motorcycles के साथ मिलकर विकसित",
  "Combined braking system": "कंबाइंड ब्रेकिंग सिस्टम",
  "Commuter-focused": "कम्यूटर-केंद्रित",
  "Compact city runabout": "कॉम्पैक्ट सिटी रनअबाउट",
  "Compact commuter": "कॉम्पैक्ट कम्यूटर",
  "Compact low-speed commuter": "कॉम्पैक्ट लो-स्पीड कम्यूटर",
  "Compact luxury SUV": "कॉम्पैक्ट लग्जरी SUV",
  "Connected app": "कनेक्टेड ऐप",
  "Connected car tech": "कनेक्टेड कार टेक",
  "Connected features": "कनेक्टेड फीचर्स",
  "Connected tech": "कनेक्टेड टेक",
  "Coupe-SUV styling": "कूपे-SUV स्टाइलिंग",
  "Cruise control": "क्रूज़ कंट्रोल",
  "Cruise control, reverse assist": "क्रूज़ कंट्रोल, रिवर्स असिस्ट",
  "Crystal headlights": "क्रिस्टल हेडलाइट्स",
  "CTB cell-to-body design": "CTB सेल-टू-बॉडी डिज़ाइन",
  "Curved display": "कर्व्ड डिस्प्ले",
  "Daily-use commuter focus": "रोज़ाना उपयोग कम्यूटर फोकस",
  "Dash cams": "डैश कैम",
  "Deepview display": "डीपव्यू डिस्प्ले",
  "Detachable battery": "निकालने योग्य बैटरी",
  "Digital cluster": "डिजिटल क्लस्टर",
  "Digital console": "डिजिटल कंसोल",
  "Digital instrument cluster": "डिजिटल इंस्ट्रूमेंट क्लस्टर",
  "Disc brakes front & rear": "आगे और पीछे डिस्क ब्रेक",
  "Dolby Atmos audio": "Dolby Atmos ऑडियो",
  "Drag/reverse mode": "ड्रैग/रिवर्स मोड",
  "DSC and ABS": "DSC और ABS",
  "Dual 10.25-inch screens": "डुअल 10.25-inch स्क्रीन",
  "Dual 12.3-inch curved displays": "डुअल 12.3-inch कर्व्ड डिस्प्ले",
  "Dual 12.3-inch screens": "डुअल 12.3-inch स्क्रीन",
  "Dual removable 3 kWh batteries": "डुअल निकालने योग्य 3 kWh बैटरी",
  "Dual swappable batteries": "डुअल स्वैपेबल बैटरी",
  "Dual USB ports": "डुअल USB पोर्ट",
  "Dual-channel ABS": "डुअल-चैनल ABS",
  "Dual-motor AWD": "डुअल-मोटर AWD",
  "Dual-motor quattro AWD": "डुअल-मोटर quattro AWD",
  "Dual-screen setup": "डुअल-स्क्रीन सेटअप",
  "Dynamic stability control": "डायनामिक स्टेबिलिटी कंट्रोल",
  "e Vitara twin": "e Vitara ट्विन",
  "Eco/City modes": "Eco/City मोड",
  "Eco/City/Havoc modes": "Eco/City/Havoc मोड",
  "Eco/City/Sport modes": "Eco/City/Sport मोड",
  "Eco/Normal/Sport + reverse": "Eco/Normal/Sport + रिवर्स",
  "Eco/Power/Sport modes": "Eco/Power/Sport मोड",
  "Eco/Ride/Sport modes": "Eco/Ride/Sport मोड",
  "Eco/Sport modes": "Eco/Sport मोड",
  "EcoX and SonicX modes": "EcoX और SonicX मोड",
  "Electric cruiser styling": "इलेक्ट्रिक क्रूज़र स्टाइलिंग",
  "Electric hyper-SUV": "इलेक्ट्रिक हाइपर-SUV",
  "Electric roadster with scissor doors": "सिज़र डोर वाला इलेक्ट्रिक रोडस्टर",
  "Electric sunroof": "इलेक्ट्रिक सनरूफ",
  "Entry BMW EV": "एंट्री BMW EV",
  "Entry Mercedes EV SUV": "एंट्री Mercedes EV SUV",
  "Entry Orbiter": "एंट्री Orbiter",
  "Executive Lounge": "एग्जीक्यूटिव लाउंज",
  "Executive rear seats": "एग्जीक्यूटिव रियर सीट्स",
  "Expected debut late 2026": "लेट 2026 में संभावित डेब्यू",
  "Expected ~450 km range": "संभावित ~450 km रेंज",
  "Family commuter": "फैमिली कम्यूटर",
  "Family scooter": "फैमिली स्कूटर",
  "Family-focused design": "फैमिली-केंद्रित डिज़ाइन",
  "Family-oriented design": "फैमिली-उन्मुख डिज़ाइन",
  "Fast 3-hour charge": "तेज़ 3-घंटे चार्ज",
  "Fast 30-min charge claim": "तेज़ 30-min चार्ज का दावा",
  "Fast charging": "फास्ट चार्जिंग",
  "Fast charging 0-80% in 45 min": "फास्ट चार्जिंग 0-80% 45 min में",
  "Faster charging": "तेज़ चार्जिंग",
  "Fighter-jet cockpit design": "फाइटर-जेट कॉकपिट डिज़ाइन",
  "First dedicated 7-seat mass-market EV": "पहली समर्पित 7-सीट मास-मार्केट EV",
  "First e-scooter with ABS": "ABS वाला पहला e-स्कूटर",
  "Five colour options": "पांच रंग विकल्प",
  "Five riding modes": "पांच राइडिंग मोड",
  "Fixed battery": "फिक्स्ड बैटरी",
  "Flagship electric 7 Series": "फ्लैगशिप इलेक्ट्रिक 7 Series",
  "Flagship electric sedan": "फ्लैगशिप इलेक्ट्रिक सेडान",
  "Flagship electric SUV": "फ्लैगशिप इलेक्ट्रिक SUV",
  "Four colour options": "चार रंग विकल्प",
  "Four power modes": "चार पावर मोड",
  "Four ride modes": "चार राइड मोड",
  "Four traction control modes": "चार ट्रैक्शन कंट्रोल मोड",
  "Fresh facelift design": "नया फेसलिफ्ट डिज़ाइन",
  "Front & rear disc": "फ्रंट और रियर डिस्क",
  "Front & rear disc brakes": "फ्रंट और रियर डिस्क ब्रेक",
  "Front disc brake": "फ्रंट डिस्क ब्रेक",
  "Front ventilated seats": "फ्रंट वेंटिलेटेड सीटें",
  "Full digital cluster": "फुल डिजिटल क्लस्टर",
  "Full LED lighting": "फुल LED लाइटिंग",
  "Fully-faired bodywork": "फुली-फेयर्ड बॉडीवर्क",
  "Fully-faired sport styling": "फुली-फेयर्ड स्पोर्ट स्टाइलिंग",
  "Fully-faired tourer styling": "फुली-फेयर्ड टूअरर स्टाइलिंग",
  "FWD & AWD options": "FWD और AWD विकल्प",
  "Geo-fencing": "जियो-फेंसिंग",
  "Google built-in": "Google बिल्ट-इन",
  "Google Maps navigation": "Google Maps नेविगेशन",
  "GPS & anti-theft IoT": "GPS और एंटी-थेफ्ट IoT",
  "Gran Coupe styling": "Gran Coupe स्टाइलिंग",
  "Grand tourer styling": "ग्रैंड टूअरर स्टाइलिंग",
  "Greaves/Ampere flagship": "Greaves/Ampere फ्लैगशिप",
  "Harman Kardon audio": "Harman Kardon ऑडियो",
  "Highest range in segment": "सेगमेंट में सबसे ज़्यादा रेंज",
  "Highland facelift CBU": "Highland फेसलिफ्ट CBU",
  "Highway Assistant": "हाईवे असिस्टेंट",
  "Hill hold": "हिल होल्ड",
  "Hill Start Assist": "हिल स्टार्ट असिस्ट",
  "Honda swap network": "Honda स्वैप नेटवर्क",
  "Hub-mounted 4.5 kW motor": "हब-माउंटेड 4.5 kW मोटर",
  "India's fastest e-scooter": "भारत का सबसे तेज़ e-स्कूटर",
  "India's first electric enduro": "भारत की पहली इलेक्ट्रिक एंड्यूरो",
  "India's first geared electric bike": "भारत की पहली गियर वाली इलेक्ट्रिक बाइक",
  "Indigenous 4680 Bharat Cell": "स्वदेशी 4680 Bharat Cell",
  "INGLO platform": "INGLO प्लेटफॉर्म",
  "INGLO skateboard platform": "INGLO स्केटबोर्ड प्लेटफॉर्म",
  "IoT & AI sensors": "IoT और AI सेंसर",
  "IoT connectivity": "IoT कनेक्टिविटी",
  "IP67 hub motor": "IP67 हब मोटर",
  "IP67 steel frame": "IP67 स्टील फ्रेम",
  "iTAC torque control": "iTAC टॉर्क कंट्रोल",
  "JBL audio + wireless CarPlay": "JBL ऑडियो + वायरलेस CarPlay",
  "K1 platform": "K1 प्लेटफॉर्म",
  "Keyless ignition": "कीलेस इग्निशन",
  "Keyless ignition & wireless charger": "कीलेस इग्निशन और वायरलेस चार्जर",
  "Kia's most affordable EV": "Kia की सबसे किफायती EV",
  "Large screens": "बड़ी स्क्रीन",
  "Larger range pack": "बड़ा रेंज पैक",
  "Larger touchscreen": "बड़ी टचस्क्रीन",
  "Largest battery in iQube range": "iQube रेंज में सबसे बड़ी बैटरी",
  "Launch confirmed Jan 2026": "लॉन्च Jan 2026 में पुष्ट",
  "LCD console": "LCD कंसोल",
  "LED lighting": "LED लाइटिंग",
  "Level 2 ADAS": "Level 2 ADAS",
  "Level 2 ADAS + 360 camera": "Level 2 ADAS + 360 कैमरा",
  "Level 3 autonomous-ready ADAS": "Level 3 ऑटोनॉमस-रेडी ADAS",
  "LFP battery": "LFP बैटरी",
  "LFP swappable battery": "LFP स्वैपेबल बैटरी",
  "LiDAR-based safety": "LiDAR-आधारित सुरक्षा",
  "Lifetime battery warranty": "लाइफटाइम बैटरी वारंटी",
  "Lifetime warranty": "लाइफटाइम वारंटी",
  "Lightweight": "हल्का",
  "Lightweight 113 kg": "हल्का 113 kg",
  "Lightweight 70 kg": "हल्का 70 kg",
  "Lightweight 79 kg": "हल्का 79 kg",
  "Liquid-cooled 90 kW motor": "लिक्विड-कूल्ड 90 kW मोटर",
  "Liquid-cooled battery": "लिक्विड-कूल्ड बैटरी",
  "Liquid-cooled IP67 battery": "लिक्विड-कूल्ड IP67 बैटरी",
  "Lithium-ion 72V battery": "लिथियम-आयन 72V बैटरी",
  "Long-wheelbase India version": "लॉन्ग-व्हीलबेस इंडिया वर्जन",
  "Longest 900 mm seat": "सबसे लंबी 900 mm सीट",
  "Low-frame ergonomics": "लो-फ्रेम एर्गोनॉमिक्स",
  "Low-speed (no licence)": "लो-स्पीड (बिना लाइसेंस)",
  "Luxury 7-seat electric MPV": "लग्जरी 7-सीट इलेक्ट्रिक MPV",
  "M Performance EV": "M Performance EV",
  "Made in Coimbatore": "Coimbatore में निर्मित",
  "Magic twist regen": "मैजिक ट्विस्ट रीजन",
  "MagicTwist regen": "MagicTwist रीजन",
  "Maruti's first EV": "Maruti की पहली EV",
  "Matrix LED headlights": "मैट्रिक्स LED हेडलाइट्स",
  "Maybach ultra-luxury EV": "Maybach अल्ट्रा-लग्जरी EV",
  "MBUX Hyperscreen": "MBUX Hyperscreen",
  "MBUX infotainment": "MBUX इन्फोटेनमेंट",
  "Metal body": "मेटल बॉडी",
  "Mid-size electric SUV": "मिड-साइज़ इलेक्ट्रिक SUV",
  "Modular 2.2-4.4 kWh platform": "मॉड्यूलर 2.2-4.4 kWh प्लेटफॉर्म",
  "Most affordable 450": "सबसे किफायती 450",
  "Most expensive EV in India": "भारत में सबसे महंगी EV",
  "MoveOS 5": "MoveOS 5",
  "Multi-mode regen": "मल्टी-मोड रीजन",
  "Multiple battery chemistries": "कई बैटरी केमिस्ट्री",
  "Multiple battery options": "कई बैटरी विकल्प",
  "Multiple battery tiers": "कई बैटरी टियर",
  "Multiple variants": "कई वेरिएंट",
  "Naked roadster styling": "नेकेड रोडस्टर स्टाइलिंग",
  "Naked street design": "नेकेड स्ट्रीट डिज़ाइन",
  "Naked streetfighter styling": "नेकेड स्ट्रीटफाइटर स्टाइलिंग",
  "Navigation": "नेविगेशन",
  "Navigation support": "नेविगेशन सपोर्ट",
  "New EL family platform": "नया EL फैमिली प्लेटफॉर्म",
  "No-licence 25 km/h": "बिना लाइसेंस 25 km/h",
  "Off-road modes (Rock Crawl, Boost)": "ऑफ-रोड मोड (Rock Crawl, Boost)",
  "Ohlins forks, Brembo brakes": "Ohlins फोर्क, Brembo ब्रेक",
  "Okinawa flagship": "Okinawa फ्लैगशिप",
  "OLED taillights": "OLED टेललाइट",
  "OTA updates": "OTA अपडेट",
  "OTA updates, keyless": "OTA अपडेट, कीलेस",
  "Panoramic glass roof": "पैनोरमिक ग्लास रूफ",
  "Panoramic roof": "पैनोरमिक रूफ",
  "Panoramic Sky Lounge roof": "पैनोरमिक Sky Lounge रूफ",
  "Panoramic sunroof": "पैनोरमिक सनरूफ",
  "Passenger display": "पैसेंजर डिस्प्ले",
  "Performance AWD option": "परफॉर्मेंस AWD विकल्प",
  "Pixel LED headlights": "पिक्सल LED हेडलाइट",
  "PMSM motor": "PMSM मोटर",
  "Powered tailgate": "पावर्ड टेलगेट",
  "PPE 800V platform": "PPE 800V प्लेटफॉर्म",
  "Practicality focus": "प्रैक्टिकैलिटी पर फोकस",
  "Premium build": "प्रीमियम बिल्ड",
  "Premium compact SUV": "प्रीमियम कॉम्पैक्ट SUV",
  "Premium e-motorcycle": "प्रीमियम e-मोटरसाइकिल",
  "Pro Pack option": "Pro Pack विकल्प",
  "Radar ADAS (blind-spot/collision)": "रडार ADAS (ब्लाइंड-स्पॉट/कोलिज़न)",
  "RE's first EV": "RE की पहली EV",
  "Rear camera": "रियर कैमरा",
  "Rear-axle steering": "रियर-एक्सल स्टीयरिंग",
  "Reclining rear seats": "रिक्लाइनिंग रियर सीट",
  "Regenerative braking": "रीजनरेटिव ब्रेकिंग",
  "Removable batteries": "निकालने योग्य बैटरियां",
  "Removable battery": "निकालने योग्य बैटरी",
  "Removable dual batteries": "निकालने योग्य डुअल बैटरियां",
  "Removable IP67 battery": "निकालने योग्य IP67 बैटरी",
  "Reverse mode": "रिवर्स मोड",
  "Ride-by-wire": "राइड-बाय-वायर",
  "Rotating 12.8-inch screen": "घूमने वाली 12.8-inch स्क्रीन",
  "Rotating 12.8-inch touchscreen": "घूमने वाली 12.8-inch टचस्क्रीन",
  "Rotating touchscreen": "घूमने वाली टचस्क्रीन",
  "Round 9.4-inch OLED display": "गोल 9.4-inch OLED डिस्प्ले",
  "RS variant available": "RS वैरिएंट उपलब्ध",
  "RWD & AWD options": "RWD & AWD विकल्प",
  "RWD, 4S & Turbo variants": "RWD, 4S & Turbo वैरिएंट",
  "S and R variants": "S और R वैरिएंट",
  "SE All4 AWD option": "SE All4 AWD विकल्प",
  "Side-stand sensor": "साइड-स्टैंड सेंसर",
  "Single electric motor": "सिंगल इलेक्ट्रिक मोटर",
  "Smart charger": "स्मार्ट चार्जर",
  "Smartphone connectivity": "स्मार्टफोन कनेक्टिविटी",
  "Sold via MG Select": "MG Select के जरिए बिक्री",
  "Spacious budget hatch": "विशाल बजट हैच",
  "Spans entry to performance": "एंट्री से परफॉर्मेंस तक",
  "Sports/Normal/Eco modes": "Sports/Normal/Eco मोड",
  "Sporty Aerox styling": "स्पोर्टी Aerox स्टाइलिंग",
  "Sporty styling": "स्पोर्टी स्टाइलिंग",
  "Starlight doors": "स्टारलाइट डोर",
  "Streamliner aero design": "स्ट्रीमलाइनर एयरो डिज़ाइन",
  "Sub Rs 1 lakh expected": "Rs 1 लाख से कम संभावित",
  "Sub-compact electric SUV": "सब-कॉम्पैक्ट इलेक्ट्रिक SUV",
  "Supercharger network": "सुपरचार्जर नेटवर्क",
  "Sustainable cabin materials": "टिकाऊ केबिन मटेरियल",
  "SUV-style rugged design": "SUV-स्टाइल रगेड डिज़ाइन",
  "Suzuki's first India EV": "Suzuki की पहली India EV",
  "Swappable battery expected": "स्वैपेबल बैटरी संभावित",
  "Switchable dual-channel ABS": "स्विचेबल डुअल-चैनल ABS",
  "TFT display": "TFT डिस्प्ले",
  "TFT touchscreen": "TFT टचस्क्रीन",
  "Three battery options": "तीन बैटरी विकल्प",
  "Three colour options": "तीन कलर विकल्प",
  "Three ride modes": "तीन राइड मोड",
  "Tiny urban footprint": "छोटा अर्बन फुटप्रिंट",
  "Top speed 141 km/h": "टॉप स्पीड 141 km/h",
  "Top speed ~194 km/h": "टॉप स्पीड ~194 km/h",
  "TPMS": "TPMS",
  "Track mode": "ट्रैक मोड",
  "Trellis frame, USD forks": "ट्रेलिस फ्रेम, USD फोर्क",
  "Trip statistics": "ट्रिप आंकड़े",
  "Triple 12.3-inch screens": "तीन 12.3-inch स्क्रीन",
  "Triple-screen setup": "ट्रिपल-स्क्रीन सेटअप",
  "Tubular crash guard": "ट्यूबलर क्रैश गार्ड",
  "Turbo mode": "Turbo मोड",
  "Turbo variants available": "Turbo वैरिएंट उपलब्ध",
  "Turn-by-turn navigation": "टर्न-बाय-टर्न नेविगेशन",
  "Twin 10.25-inch screens": "ट्विन 10.25-inch स्क्रीन",
  "Twin projector LED headlights": "ट्विन प्रोजेक्टर LED हेडलाइट",
  "Twin-pod headlight": "ट्विन-पॉड हेडलाइट",
  "Ultra-fast 350kW charging": "अल्ट्रा-फास्ट 350kW चार्जिंग",
  "Ultra-luxury electric coupe": "अल्ट्रा-लग्जरी इलेक्ट्रिक कूपे",
  "Up to 248 km range variants": "248 km तक रेंज वाले वैरिएंट",
  "Up to 250 km range variant": "250 km तक रेंज वाला वैरिएंट",
  "Up to 3 kWh battery": "3 kWh तक की बैटरी",
  "Up to 5.15 kWh battery": "5.15 kWh तक की बैटरी",
  "Up to 6 kWh / 261 km": "6 kWh / 261 km तक",
  "Up to 639 PS Turbo": "639 PS तक Turbo",
  "Up to 668 km range": "668 km तक रेंज",
  "Up to 7-seat luxury SUV": "7-सीट तक लग्जरी SUV",
  "USB-C charging": "USB-C चार्जिंग",
  "USD front forks": "USD फ्रंट फोर्क",
  "V2L and V2V": "V2L और V2V",
  "V2L capability": "V2L क्षमता",
  "V2L functionality": "V2L फंक्शनैलिटी",
  "V2L power export": "V2L पावर एक्सपोर्ट",
  "V2L/V2V capability": "V2L/V2V क्षमता",
  "V2V and V2L functionality": "V2V और V2L फंक्शनैलिटी",
  "Value/family focus": "वैल्यू/फैमिली पर फोकस",
  "Ventilated seats": "वेंटिलेटेड सीट",
  "Vertical centre touchscreen": "वर्टिकल सेंटर टचस्क्रीन",
  "Virtual exterior mirrors option": "वर्चुअल एक्सटीरियर मिरर विकल्प",
  "Voice assist": "वॉइस असिस्ट",
  "Warp Drive mode": "Warp Drive मोड",
  "Warp mode": "Warp मोड",
  "Wire-spoke 19/17-inch wheels": "वायर-स्पोक 19/17-inch व्हील",
  "Wireless Android Auto/CarPlay": "वायरलेस Android Auto/CarPlay",
  "Wireless charging": "वायरलेस चार्जिंग",
  "Yamaha India EV": "Yamaha India EV",
  "Yamaha's first India EV": "Yamaha की पहली India EV",
  "~4 kW rated output": "~4 kW रेटेड आउटपुट",
};

/** Return the Hindi feature label, falling back to English if untranslated. */
export function featureHi(feature: string): string {
  return FEATURE_HI[feature] ?? feature;
}
